# Generated by Django 2.2.6 on 2019-10-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='slug',
        ),
    ]
