# Generated by Django 2.2.6 on 2019-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20191207_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='published',
            new_name='main_text',
        ),
        migrations.AlterField(
            model_name='contents',
            name='images',
            field=models.ManyToManyField(blank=True, to='contents.Images'),
        ),
    ]
